// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BackupDB(arg1) {
  return window['go']['main']['App']['BackupDB'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetProjects() {
  return window['go']['main']['App']['GetProjects']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetVersions() {
  return window['go']['main']['App']['GetVersions']();
}

export function InstallApp(arg1) {
  return window['go']['main']['App']['InstallApp'](arg1);
}

export function OpenCmdWWW() {
  return window['go']['main']['App']['OpenCmdWWW']();
}

export function OpenExternal(arg1) {
  return window['go']['main']['App']['OpenExternal'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function OpenLog(arg1) {
  return window['go']['main']['App']['OpenLog'](arg1);
}

export function OpenPMA() {
  return window['go']['main']['App']['OpenPMA']();
}

export function RebuildSSL() {
  return window['go']['main']['App']['RebuildSSL']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function Start(arg1) {
  return window['go']['main']['App']['Start'](arg1);
}

export function StartDB(arg1) {
  return window['go']['main']['App']['StartDB'](arg1);
}

export function StartMail() {
  return window['go']['main']['App']['StartMail']();
}

export function StartPgSQL(arg1) {
  return window['go']['main']['App']['StartPgSQL'](arg1);
}

export function StartRedis() {
  return window['go']['main']['App']['StartRedis']();
}

export function StartTunnel(arg1) {
  return window['go']['main']['App']['StartTunnel'](arg1);
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}

export function StopAll() {
  return window['go']['main']['App']['StopAll']();
}

export function StopDB() {
  return window['go']['main']['App']['StopDB']();
}

export function StopMail() {
  return window['go']['main']['App']['StopMail']();
}

export function StopPgSQL() {
  return window['go']['main']['App']['StopPgSQL']();
}

export function StopRedis() {
  return window['go']['main']['App']['StopRedis']();
}

export function StopTunnel(arg1) {
  return window['go']['main']['App']['StopTunnel'](arg1);
}

export function StopTunnelAll() {
  return window['go']['main']['App']['StopTunnelAll']();
}
