// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BackupDB(arg1:number):Promise<void>;

export function DeleteProject(arg1:string):Promise<void>;

export function GetAppVersion():Promise<string>;

export function GetProjects():Promise<Array<string>>;

export function GetSettings():Promise<main.Config>;

export function GetVersions():Promise<Record<string, any>>;

export function InstallApp(arg1:main.InstallData):Promise<void>;

export function OpenCmdWWW():Promise<void>;

export function OpenExternal(arg1:string):Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function OpenLog(arg1:string):Promise<void>;

export function OpenPMA():Promise<void>;

export function RebuildSSL():Promise<void>;

export function SaveSettings(arg1:Record<string, string>):Promise<Record<string, any>>;

export function Start(arg1:number):Promise<void>;

export function StartDB(arg1:number):Promise<void>;

export function StartMail():Promise<void>;

export function StartPgSQL(arg1:number):Promise<void>;

export function StartRedis():Promise<void>;

export function StartTunnel(arg1:main.TunnelData):Promise<main.TunnelResult>;

export function Stop():Promise<void>;

export function StopAll():Promise<void>;

export function StopDB():Promise<void>;

export function StopMail():Promise<void>;

export function StopPgSQL():Promise<void>;

export function StopRedis():Promise<void>;

export function StopTunnel(arg1:string):Promise<void>;

export function StopTunnelAll():Promise<void>;
